kind: pipeline
type: docker
name: plugin-build-and-push

steps:
  - name: test
    image: golang
    commands:
      - go test ./...
    environment:
      GOPATH: ''
      CGO_ENABLED: 0

  - name: build
    image: golang
    commands:
      - GOOS=linux GOARCH=amd64 go build -o release/linux/amd64/plugin
      - GOOS=linux GOARCH=arm64 go build -o release/linux/arm64/plugin
    environment:
      GOPATH: ''
      CGO_ENABLED: 0

  - name: publish
    image: plugins/docker
    settings:
      repo: quay.io/kameshsampath/drone-gcloud-run
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: publish_arm
    image: plugins/docker
    settings:
      repo: quay.io/kameshsampath/drone-gcloud-run
      auto_tag: true
      auto_tag_suffix: linux-arm64
      dockerfile: docker/Dockerfile.linux.arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: manifest
    image: plugins/manifest
    settings:
      spec: docker/manifest.tmpl
      auto_tag: true
      ignore_missing: true
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
