kind: pipeline
type: docker
name: update-and-make-service-unauthenticated

environment: &buildEnv
  SERVICE_ACCOUNT_JSON:
    from_secret: SERVICE_ACCOUNT_JSON
  GOOGLE_CLOUD_PROJECT:
     from_secret: GOOGLE_CLOUD_PROJECT
  GOOGLE_CLOUD_REGION:
     from_secret: GOOGLE_CLOUD_REGION

steps:
- name: update service to allow unauthenticated
  image: docker.io/kameshsampath/drone-gcloud-run
  settings:
    service_account_json: ${SERVICE_ACCOUNT_JSON}
    project: ${GOOGLE_CLOUD_PROJECT}
    region: ${GOOGLE_CLOUD_REGION}
    service_name: my-service
    image: asia.gcr.io/${GOOGLE_CLOUD_PROJECT}/greeter
    allow_unauthenticated: true
  environment: *buildEnv
